version: '3.8'

services:
  nextjs:
    container_name: nextjs.dev
    # image: 192.168.3.200:80/library/node:19.8.1
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: unless-stopped
